[versions]
protobuf = "3.25.5"
protobufPlugin = "0.9.4"
kafka = "3.7.1"
deephaven = "0.36.1"
iceberg = "1.5.2"
slf4j = "2.0.13"
logback = "1.5.6"
junit = "5.10.2"
assertj = "3.26.0"
picocli = "4.7.6"

[libraries]
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
protobuf-java-util = { module = "com.google.protobuf:protobuf-java-util", version.ref = "protobuf" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }

[plugins]
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
